### ISSUE TITLE
Startup error after upgrade to fe06767

### ISSUE THREAD

**Issue by bernd** [graylog-labs/graylog-plugin-netflow#12]
My netflow input does not start after updating to rev fe06767 of the netflow plugin.
```
2017-07-26 12:23:49,601 ERROR: org.graylog2.shared.inputs.InputLauncher - The [org.graylog.plugins.netflow.inputs.NetFlowUdpInput] input with ID <59707142833ee75bb43c2faa> misfired. Reason: Mandatory configuration field cache_size is missing or has the wrong data type.
org.graylog2.plugin.configuration.ConfigurationException: Mandatory configuration field cache_size is missing or has the wrong data type
         at org.graylog2.plugin.configuration.ConfigurationRequest.check(ConfigurationRequest.java:111) ~[graylog.jar:?]
         at org.graylog2.plugin.inputs.MessageInput.checkConfiguration(MessageInput.java:145) ~[graylog.jar:?]
         at org.graylog2.shared.inputs.InputLauncher$1.run(InputLauncher.java:82) [graylog.jar:?]
         at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176) [graylog.jar:?]
         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
         at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
         at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
2017-07-26 12:23:49,630 INFO : org.graylog2.inputs.InputStateListener - Input [NetFlow UDP/59707142833ee75bb43c2faa] is now FAILED
```

Can we make use of the default settings if the config settings are missing?

**Comment by joschi** [comment]
> Can we make use of the default settings if the config settings are missing?

We could make the settings optional, but that kind of defeats the purpose of having mandatory settings.

As far as I see there is simply no migration path for adding mandatory configuration settings to existing inputs/transports/codecs. 🤔

**Comment by bernd** [comment]
@joschi Okay, bummer. Then we should at least document this in the changelog.
